scalaVersion := "3.3.6"

name := "aws-workshop"
version := "1.0"


libraryDependencies ++= Seq(
  "software.amazon.awssdk" % "s3" % "2.32.2",
"software.amazon.awssdk" % "protocol-core" % "2.32.2",
"software.amazon.awssdk" % "http-auth-aws" % "2.32.2",
"software.amazon.awssdk" % "aws-json-protocol" % "2.32.2",
"software.amazon.awssdk" % "sts" % "2.32.2",
"software.amazon.awssdk" % "dynamodb" % "2.32.2",
"software.amazon.awssdk" % "apache-client" % "2.32.2",
"software.amazon.awssdk" % "auth" % "2.32.2",
"software.amazon.awssdk" % "netty-nio-client" % "2.32.2",
"software.amazon.awssdk" % "url-connection-client" % "2.32.2",
"software.amazon.awssdk" % "sqs" % "2.32.2",
"software.amazon.awssdk" % "regions" % "2.32.2",
"software.amazon.awssdk" % "sdk-core" % "2.32.2",
"software.amazon.awssdk" % "utils" % "2.32.2",
"software.amazon.awssdk" % "secretsmanager" % "2.32.2",
"software.amazon.awssdk" % "sns" % "2.32.2" % Test,
"software.amazon.awssdk" % "kinesis" % "2.32.2",
"software.amazon.awssdk" % "lambda" % "2.32.2",
"software.amazon.awssdk" % "cloudwatch" % "2.32.2",
"software.amazon.awssdk" % "iam" % "2.32.2" % Test,
"software.amazon.awssdk" % "kms" % "2.32.2",
"software.amazon.awssdk" % "sso" % "2.32.2",
"software.amazon.awssdk" % "ec2" % "2.32.2" % Test,
"software.amazon.awssdk" % "ssooidc" % "2.32.2",
"software.amazon.awssdk" % "http-auth-spi" % "2.32.2",
"software.amazon.awssdk" % "third-party-jackson-core" % "2.32.2",
"software.amazon.awssdk" % "rds" % "2.32.2",
"software.amazon.awssdk" % "ses" % "2.32.2",
"software.amazon.awssdk" % "cloudformation" % "2.32.2",
"software.amazon.awssdk" % "aws-xml-protocol" % "2.32.2",
"software.amazon.awssdk" % "route53" % "2.32.2",
"software.amazon.awssdk" % "ecs" % "2.32.2",
"software.amazon.awssdk" % "ecr" % "2.32.2",
"software.amazon.awssdk" % "acm" % "2.32.2",
"software.amazon.awssdk" % "apigateway" % "2.32.2",
"software.amazon.awssdk" % "bedrock" % "2.32.2",
"software.amazon.awssdk" % "elasticloadbalancingv2" % "2.32.2",
"software.amazon.awssdk" % "elasticbeanstalk" % "2.32.2",
"software.amazon.awssdk" % "autoscaling" % "2.32.2",
"software.amazon.awssdk" % "iam-policy-builder" % "2.32.2",
"software.amazon.awssdk" % "apigatewayv2" % "2.32.2",
"software.amazon.awssdk" % "elasticloadbalancing" % "2.32.2",
"software.amazon.awssdk" % "sesv2" % "2.32.2",
"software.amazon.awssdk" % "cloudtrail" % "2.32.2",
"software.amazon.awssdk" % "cognitoidentity" % "2.32.2",
"software.amazon.awssdk" % "eks" % "2.32.2",
"software.amazon.awssdk" % "servicediscovery" % "2.32.2",
"software.amazon.awssdk" % "aws-cbor-protocol" % "2.32.2",
"software.amazon.awssdk" % "elasticache" % "2.32.2",
"software.amazon.awssdk" % "lightsail" % "2.32.2",
"software.amazon.awssdk" % "applicationautoscaling" % "2.32.2",
"software.amazon.awssdk" % "waf" % "2.32.2",
"software.amazon.awssdk" % "kafka" % "2.32.2",
"software.amazon.awssdk" % "s3tables" % "2.32.2",
"software.amazon.awssdk" % "apache-client" % "2.32.2",
"software.amazon.awssdk" % "account" % "2.32.2",
"software.amazon.awssdk" % "cloudhsm" % "2.32.2",
"software.amazon.awssdk" % "privatenetworks" % "2.31.48",
"software.amazon.awssdk" % "paymentcryptography" % "2.32.2",
"software.amazon.awssdk" % "ebs" % "2.32.2",
"software.amazon.awssdk" % "resourcegroups" % "2.32.2",
"software.amazon.awssdk" % "identitystore" % "2.32.2",
"software.amazon.awssdk" % "memorydb" % "2.32.2",
"software.amazon.awssdk" % "ssoadmin" % "2.32.2",
"software.amazon.awssdk" % "applicationinsights" % "2.32.2",
"software.amazon.awssdk" % "grafana" % "2.32.2",
"software.amazon.awssdk" % "wafv2" % "2.32.2",
"software.amazon.awssdk" % "sns" % "2.32.2",

)

